/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Andrés
 */
public class VentanaAhorcado extends javax.swing.JFrame {
    
    //Creamos la lista de palabras para jugar.
    String palabraOculta = "CETYS";
    String [] listaPalabras = {"CETYS","ORDENADOR", "LAMPARA", "MOVIL", "PLUTON", "MESA", "coche", "torneo", "profesor", "gafas", "puerto", "gorrion"};
    int numeroFallos = 0;

    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        dibujaImagen(0); //Llamamos dibuja imagen para que alga la imagen
        
        //Al igualar palabraOculta al string le decimos que cuando llame a la palabra de la lista de palabras las guarde alli.
        palabraOculta = eligePalabraOculta(listaPalabras); //Llamamos a la lista de palabras, una de ellas.
        palabraOculta = palabraOculta.toUpperCase(); //Esto es para que si en la lista hay una palabra en minusculas, las ponga en mayusculas.
        escribeGuinesEnPantalla(); //Para poner los guines que hagan falta
        System.out.println(palabraOculta);
    }
    
    //Con este metodo se escibre en pantalla el numero de guiones como letras tenga la palabra.
    private void escribeGuinesEnPantalla () {
       String auxiliar = "";
       for (int i = 0; i < palabraOculta.length(); i++) {
           auxiliar = auxiliar + "_ ";
       }
       pantalla.setText (auxiliar);
    }
    
    private String eligePalabraOculta (String [] lista) {
        Random aleatorio = new Random();
        return lista [aleatorio.nextInt (lista.length)];
    }
    //Metodo para revisar si la letra presionada esta en la palabra oculta, si no es asi nos devuelve un fallo.
    private void chequeaLetra (String letra) {
        letra = letra.toUpperCase();
        StringBuilder palabraConGuiones = new StringBuilder (pantalla.getText());
        
        //La letra si esta.
        if (palabraOculta.contains(letra)) {
            for (int i = 0; i < palabraOculta.length(); i++) { //Con este for nos grarantizamos que si la letra se repite, aparezca en la pantalla.
                if (palabraOculta.charAt(i) == letra.charAt(0)) {
                    palabraConGuiones.setCharAt(i * 2, letra.charAt(0));
                }
            }
            pantalla.setText(palabraConGuiones.toString());
        }
        
        else {
            
            //Al sumar un fallo nos cambia la imagen para ir viendo cuantos fallos llevamos.
            numeroFallos++;
        }
        
         dibujaImagen(numeroFallos);
    }
    
    //Metodo para dibujar la imagen en el panel.
    private void dibujaImagen (int numeroImagen) {
        
         URL nombreImagen = null;
        if (!pantalla.getText().contains("_")){
            nombreImagen = getClass ().getResource("/imagenes/acertasteTodo.png");
        }
        
        else {
            //Introducimos el swicht que lo que hace es mejorar los if anidados, queda el codigo mas legible.
            switch (numeroImagen) {
                case 0: nombreImagen = getClass ().getResource("/imagenes/ahorcado_0.png"); break;
                case 1: nombreImagen = getClass ().getResource("/imagenes/ahorcado_1.png"); break;
                case 2: nombreImagen = getClass ().getResource("/imagenes/ahorcado_2.png"); break;
                case 3: nombreImagen = getClass ().getResource("/imagenes/ahorcado_3.png"); break;
                case 4: nombreImagen = getClass ().getResource("/imagenes/ahorcado_4.png"); break;
                case 5: nombreImagen = getClass ().getResource("/imagenes/ahorcado_5.png"); break;
                case 6: nombreImagen = getClass ().getResource("/imagenes/ahorcado_fin.png"); break; 
                default : nombreImagen = getClass ().getResource("/imagenes/ahorcado_lose.jpg");
            }
        }
        int ancho = panel.getWidth();
        int alto = panel.getHeight();
        ImageIcon miImagen =new ImageIcon (new ImageIcon (nombreImagen).getImage().getScaledInstance(ancho, alto, Image.SCALE_DEFAULT));
        panel.setIcon(miImagen);
    }
    
    //Metodo para revisar el boton que se a presionado, y nos imprime la letra que este boton contiene.
    private void chequeaBoton (JButton miBoton) {
        miBoton.setEnabled(false);
        chequeaLetra(miBoton.getText());
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        panel = new javax.swing.JLabel();
        LETRA1 = new javax.swing.JButton();
        LETRA2 = new javax.swing.JButton();
        LETRA3 = new javax.swing.JButton();
        LETRA4 = new javax.swing.JButton();
        LETRA5 = new javax.swing.JButton();
        LETRA6 = new javax.swing.JButton();
        LETRA7 = new javax.swing.JButton();
        LETRA8 = new javax.swing.JButton();
        LETRA9 = new javax.swing.JButton();
        LETRA10 = new javax.swing.JButton();
        LETRA11 = new javax.swing.JButton();
        LETRA12 = new javax.swing.JButton();
        LETRA13 = new javax.swing.JButton();
        LETRA14 = new javax.swing.JButton();
        LETRA15 = new javax.swing.JButton();
        LETRA16 = new javax.swing.JButton();
        LETRA17 = new javax.swing.JButton();
        LETRA18 = new javax.swing.JButton();
        LETRA19 = new javax.swing.JButton();
        LETRA20 = new javax.swing.JButton();
        LETRA21 = new javax.swing.JButton();
        LETRA22 = new javax.swing.JButton();
        LETRA23 = new javax.swing.JButton();
        LETRA24 = new javax.swing.JButton();
        LETRA25 = new javax.swing.JButton();
        LETRA26 = new javax.swing.JButton();
        LETRA27 = new javax.swing.JButton();
        LETRA28 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pantalla.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pantalla.setText("_ _ _ _ _");

        LETRA1.setText("A");
        LETRA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA1MousePressed(evt);
            }
        });

        LETRA2.setText("B");
        LETRA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA2MousePressed(evt);
            }
        });

        LETRA3.setText("C");
        LETRA3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA3MousePressed(evt);
            }
        });

        LETRA4.setText("D");
        LETRA4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA4MousePressed(evt);
            }
        });

        LETRA5.setText("E");
        LETRA5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA5MousePressed(evt);
            }
        });

        LETRA6.setText("F");
        LETRA6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA6MousePressed(evt);
            }
        });

        LETRA7.setText("G");
        LETRA7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA7MousePressed(evt);
            }
        });

        LETRA8.setText("I");
        LETRA8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA8MousePressed(evt);
            }
        });

        LETRA9.setText("J");
        LETRA9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA9MousePressed(evt);
            }
        });

        LETRA10.setText("K");
        LETRA10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA10MousePressed(evt);
            }
        });

        LETRA11.setText("L");
        LETRA11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA11MousePressed(evt);
            }
        });

        LETRA12.setText("M");
        LETRA12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA12MousePressed(evt);
            }
        });

        LETRA13.setText("N");
        LETRA13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA13MousePressed(evt);
            }
        });

        LETRA14.setText("H");
        LETRA14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA14MousePressed(evt);
            }
        });

        LETRA15.setText("O");
        LETRA15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA15MousePressed(evt);
            }
        });

        LETRA16.setText("P");
        LETRA16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA16MousePressed(evt);
            }
        });

        LETRA17.setText("Q");
        LETRA17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA17MousePressed(evt);
            }
        });

        LETRA18.setText("R");
        LETRA18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA18MousePressed(evt);
            }
        });

        LETRA19.setText("S");
        LETRA19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA19MousePressed(evt);
            }
        });

        LETRA20.setText("T");
        LETRA20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA20MousePressed(evt);
            }
        });

        LETRA21.setText("Ñ");
        LETRA21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA21MousePressed(evt);
            }
        });

        LETRA22.setText("V");
        LETRA22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA22MousePressed(evt);
            }
        });

        LETRA23.setText("W");
        LETRA23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA23MousePressed(evt);
            }
        });

        LETRA24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA24MousePressed(evt);
            }
        });

        LETRA25.setText("X");
        LETRA25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA25MousePressed(evt);
            }
        });

        LETRA26.setText("Y");
        LETRA26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA26MousePressed(evt);
            }
        });

        LETRA27.setText("Z");
        LETRA27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA27MousePressed(evt);
            }
        });

        LETRA28.setText("U");
        LETRA28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LETRA28MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pantalla, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LETRA28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA26, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA27, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LETRA21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LETRA14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LETRA1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LETRA7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LETRA1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LETRA14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LETRA21, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA18, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA19, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA20, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LETRA28, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA22, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA23, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA26, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LETRA27, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LETRA1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA1MousePressed
        chequeaBoton ((JButton) evt.getSource()); //Con este metodo lo que hacemos es que cuando presionemos la letra independentemente del resultado, esta se queda presionada para 
                                                  // ver que esa letra ya a sido presionado y no volver a presionarla.
    }//GEN-LAST:event_LETRA1MousePressed

    private void LETRA2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA2MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA2MousePressed

    private void LETRA3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA3MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA3MousePressed

    private void LETRA4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA4MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA4MousePressed

    private void LETRA5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA5MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA5MousePressed

    private void LETRA6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA6MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA6MousePressed

    private void LETRA7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA7MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA7MousePressed

    private void LETRA8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA8MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA8MousePressed

    private void LETRA9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA9MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA9MousePressed

    private void LETRA10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA10MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA10MousePressed

    private void LETRA11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA11MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA11MousePressed

    private void LETRA12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA12MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA12MousePressed

    private void LETRA13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA13MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA13MousePressed

    private void LETRA14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA14MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA14MousePressed

    private void LETRA15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA15MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA15MousePressed

    private void LETRA16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA16MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA16MousePressed

    private void LETRA17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA17MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA17MousePressed

    private void LETRA18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA18MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA18MousePressed

    private void LETRA19MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA19MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA19MousePressed

    private void LETRA20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA20MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA20MousePressed

    private void LETRA21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA21MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA21MousePressed

    private void LETRA22MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA22MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA22MousePressed

    private void LETRA23MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA23MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA23MousePressed

    private void LETRA24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA24MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA24MousePressed

    private void LETRA25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA25MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA25MousePressed

    private void LETRA26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA26MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA26MousePressed

    private void LETRA27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA27MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA27MousePressed

    private void LETRA28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LETRA28MousePressed
        chequeaBoton ((JButton) evt.getSource ());
    }//GEN-LAST:event_LETRA28MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LETRA1;
    private javax.swing.JButton LETRA10;
    private javax.swing.JButton LETRA11;
    private javax.swing.JButton LETRA12;
    private javax.swing.JButton LETRA13;
    private javax.swing.JButton LETRA14;
    private javax.swing.JButton LETRA15;
    private javax.swing.JButton LETRA16;
    private javax.swing.JButton LETRA17;
    private javax.swing.JButton LETRA18;
    private javax.swing.JButton LETRA19;
    private javax.swing.JButton LETRA2;
    private javax.swing.JButton LETRA20;
    private javax.swing.JButton LETRA21;
    private javax.swing.JButton LETRA22;
    private javax.swing.JButton LETRA23;
    private javax.swing.JButton LETRA24;
    private javax.swing.JButton LETRA25;
    private javax.swing.JButton LETRA26;
    private javax.swing.JButton LETRA27;
    private javax.swing.JButton LETRA28;
    private javax.swing.JButton LETRA3;
    private javax.swing.JButton LETRA4;
    private javax.swing.JButton LETRA5;
    private javax.swing.JButton LETRA6;
    private javax.swing.JButton LETRA7;
    private javax.swing.JButton LETRA8;
    private javax.swing.JButton LETRA9;
    private javax.swing.JLabel panel;
    private javax.swing.JLabel pantalla;
    // End of variables declaration//GEN-END:variables
}
